Repository replicatedhq/troubleshoot-specs, pull requests merged in 2023-04, with the labels that each got.

#62 get the rqlite database dump
  in-cluster/default-kurl.yaml
  in-cluster/default.yaml
Labels: echoes/effort: XS, type::chore

#57 add rqlite db dump collector
  in-cluster/cant-generate-bundle-with-kots.yaml
  in-cluster/default-kurl.yaml
  in-cluster/default.yaml
Labels: type::chore

#63 Merge troubleshoot specs to default host and in-cluster specs
  host/all-journald-logs.yaml
  host/cri.yaml
  host/default.yaml
  host/kubeadm-bootstrap.yaml
  host/networking-issues.yaml
  host/resource-contention.yaml
  in-cluster/cant-generate-bundle-with-kots.yaml
  in-cluster/default-kurl.yaml
  in-cluster/default.yaml
  in-cluster/ekco.yaml
  in-cluster/networking-issues-kurl.yaml
  in-cluster/no-exec.yaml
Labels: type::feature

#64 add velero logs
  in-cluster/default.yaml
Labels: type::feature
